apiVersion: apps/v1
kind: Deployment

metadata:
  name: micro-frontends

spec:
  replicas: 1

  selector:
    matchLabels:
      app: micro-frontends

  template:
    metadata:
      labels:
        app: micro-frontends

    spec:
      containers:
        - name: micro-frontends
          image: furmountain/micro-frontends:v11
          ports:
            - containerPort: 3000
